HWmathematicalClass mat = new HWmathematicalClass();
integer addResult = mat.add(7, 5);
integer subResult = mat.subtraction(12, 5);
integer multplyResult = mat.multiplication(5, 8);
integer divResult = mat.division(40, 4);

system.debug('The result of addition is: ' + addResult);
system.debug('The result of subtruction is: ' + subResult);
system.debug('The result of multplyResult is: ' + multplyResult);
system.debug('The result of divResult is: ' + divResult);



