public  class HWmathematicalClass {
    public integer add(integer a, integer b){
        integer sum = a + b;
        return sum;
    }

    public integer subtraction(integer a, integer b){
        integer difference = a - b;
        return difference;
    }

    public integer multiplication(integer a, integer b){
        integer product = a * b;
        return product;
    }

    public integer division(integer a, integer b){
        integer div = a / b;
        return div;
    }

    
}
