String firstName = 'Serpil';
String lastName = 'Atis';
String fullName = firstName + ' ' + lastName;
system.debug('my full name is ' + fullName);
////////////////////////////////////////////////
string brand = 'Honda';
string model = 'Civic';
string color = 'white';
system.debug(brand);
system.debug(model);
system.debug(color);
string myCar = brand + ' ' + model + ' ' + color;
system.debug('My car is ' + myCar);
//////////////////////////////////////////////////
