public  class Address {
    public void homeAddress(){
        String yourName = 'Serpil';
        Integer totalNumberFamily = 5;
        String houseName = 'Atis';
        Integer houseNumber = 315;
        String streetName = 'Cornerstone';
        String cityName = 'Wylie';
        String stateName = 'Texas';
        String stateISOCode = '1111111';
        String countryName = 'Collin';
        String countryISOCode = '2222222';
        String zipCode = '75098';
        Boolean currentHome = true;

        system.debug('My name is ' + yourName);
        system.debug('My total number family is ' + totalNumberFamily);
        system.debug('My house name is ' + houseName);
        system.debug('My house number is ' + houseNumber);
        system.debug('My street name is ' + streetName);
        system.debug('My city name is ' + cityName);
        system.debug('My state name is ' + stateName);
        system.debug('My state ISO code is ' + stateISOCode);
        system.debug('My country name is ' + countryName);
        system.debug('My country ISO code is ' + countryISOCode);
        system.debug('My zip code is ' + zipCode);
        system.debug('My current home is ' + currentHome);



    }


    

    
}